services:
  postgres:
    container_name: pg_user_db
    image: postgres:16
    environment:
      POSTGRES_USERNAME: ${USER_DB_USERNAME}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
      POSTGRES_DATA: /var/lib/postgresql/data
    volumes:
      - user_db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - restaurant-net
    restart: unless-stopped

  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4:7.8
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False' # Single user
    volumes:
      - pg_admin_data:/var/lib/pgadmin
    ports:
      - 5050:80
    depends_on:
      - postgres
    networks:
      - restaurant-net
    restart: unless-stopped

volumes:
  user_db_data:
  pg_admin_data:

networks:
  restaurant-net:
    driver: bridge