services:
  postgres:
    container_name: pg_user_db
    image: postgres:16
    environment:
      POSTGRES_USERNAME: ${USER_DB_USERNAME}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
      POSTGRES_DATA: /var/lib/postgresql/data
    volumes:
      - user_db_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - restaurant-net
    restart: unless-stopped

volumes:
  user_db_data:

networks:
  restaurant-net:
    driver: bridge