services:
  user-db:
    container_name: pg_user_db
    image: postgres:16
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: ${USER_DB_USERNAME}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - user_db_data:/var/lib/postgresql/data
    ports:
      - 5435:5432
    networks:
      - restaurant-net
    restart: unless-stopped

  restaurant-db:
    container_name: pg_restaurant_db
    image: postgres:16
    environment:
      POSTGRES_DB: restaurant_db
      POSTGRES_USER: ${RESTAURANT_DB_USERNAME}
      POSTGRES_PASSWORD: ${RESTAURANT_DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - restaurant_db_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - restaurant-net
    restart: unless-stopped

  order-db:
    container_name: pg_order_db
    image: postgres:16
    environment:
      POSTGRES_DB: order_db
      POSTGRES_USER: ${ORDER_DB_USERNAME}
      POSTGRES_PASSWORD: ${ORDER_DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - order_db_data:/var/lib/postgresql/data
    ports:
      - 5434:5432
    networks:
      - restaurant-net
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.4
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - restaurant-net

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: restaurant_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
    ports:
      - 9092:9092
    networks:
      - restaurant-net

volumes:
  user_db_data:
  restaurant_db_data:
  order_db_data:

networks:
  restaurant-net:
    driver: bridge